export default {
    App: {
        color: "#000000e3",
        padding: "5px",
    },
    summaryCard: {
        maxWidth: "700px",
        margin: "50px auto",
        height: "100%",
        boxShadow: "0px 0px 20px 0px #00000040",
        borderRadius: "30px",
        border: "3px solid black",
        background: "white",
    },
    firstCard: {
        maxWidth: "700px",
        margin: "50px auto",
        height: "100%",
        // boxShadow: "0px 0px 20px 0px #00000040",
        // borderRadius: "30px",
    },
    secondCard: {
        maxWidth: "700px",
        margin: "50px auto",
        boxShadow: "0px 0px 20px 0px #00000040",
        borderRadius: "30px",
        border: "3px solid #0000006b",
        background: "white",
    },
    secondCardParent: {
        position: "fixed",
        top: 0,
        right: 0,
        left: 0,
        bottom: 0,
        overflowY: "auto",
        background: "#000000b0",
        padding: "5px",
    },
    permissionBtnNo: {
        width: "80px",
        background: "#e4e3e3",
        borderRadius: "10px",
        border: "3px solid #808080a8",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        fontSize: "27px",
        cursor: "pointer",
    },
    permissionBtnYes: {
        width: "80px",
        background: "#e4e3e3",
        borderRadius: "10px",
        border: "3px solid #146A26",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        fontSize: "27px",
        cursor: "pointer",
    },
    headerImage: {
        width: "100%",
        borderRadius: "30px",
    },
    bodyMargin: {
        padding: "20px",
    },
    firstH3: {
        fontSize: "35px",
        fontWeight: 800,
        fontFamily: "Gotham-Bold",
        textAlign: "center",
        lineHeight: "32px",
        margin: 0,
    },
    firstH5: {
        fontSize: "23px",
        fontWeight: 700,
        fontFamily: "Gotham-Bold",
        textAlign: "center",
        margin: "15px 0 30px 0",
    },
    ulFontSize: {
        fontSize: "17px",
        marginBottom: "30px",
    },
    marginBottom15: {
        marginBottom: "19px",
        lineHeight: "25px",
    },
    included: {
        width: "100%",
        height: "48px",
        borderRadius: "16px",
        fontSize: "20px",
        background: "transparent",
        boxShadow: "0px 0px 10px 0px #0000006e",
        cursor: "pointer",
    },
    understand: {
        width: "100%",
        height: "48px",
        borderRadius: "16px",
        fontSize: "20px",
        background: "#06AEC1",
        color: "white",
        border: "none",
        boxShadow: "0px 0px 10px 0px #0000006e",
        cursor: "pointer",
        borderColor: "transparent",
    },
    understoodHeaderTitle: {
        textAlign: "center",
        fontSize: "32px",
        fontWeight: 700,
        margin: "23px 0",
    },
    relative: {
        position: "relative",
    },
    close: {
        position: "absolute",
        top: "2px",
        right: "15px",
        fontSize: "24px",
        cursor: "pointer",
    },
    understoodBody: {
        padding: "0 15px 15px 15px",
    },
    font20: {
        fontSize: "18px",
        padding: "3px",
        lineHeight: "22px",
    },
    fontTH20: {
        fontSize: "20px",
        color: "#146A26",
        padding: "8px",
    },
    font30: {
        fontSize: "25px",
        textAlign: "center",
        padding: "3px",
    },
    center: {
        textAlign: "center",
        padding: "8px",
    },
    understoodButton: {
        padding: "30px 8px 8px 8px",
    },
    moreTitle: {
        display: "flex",
        flexDirection: "column",
    },
    moreWant: {
        fontSize: "37px",
        fontWeight: 900,
        fontFamily: "Gotham-Bold",
        textAlign: "center",
    },
    moreUl: {
        fontSize: "20px",
        marginBottom: 0,
    },
    description: {
        padding: "10px 25px",
        fontSize: "20px",
    },
    ulDescription: {
        paddingLeft: "42px",
    },
    flex: {
        display: "flex",
        borderRadius: "25px",
        margin: "25px 0",
        position: "relative",
        background: "white",
    },
    image: {
        borderRadius: "25px 0 0 25px",
        height: "100%",
        width: "100px",
        objectFit: "contain",
    },
    padding15: {
        padding: "15px",
        width: "100%",
    },
    fontSize25: {
        fontSize: "25px",
    },
    fontSize27: {
        fontFamily: "Gotham-Bold",
        fontSize: "27px",
    },
    infoIcon: {
        position: "absolute",
        top: 0,
        right: "5px",
        fontSize: "37px",
        color: "grey",
        cursor: "pointer",
    },
    exceptDevice: {
        fontSize: "21px",
        marginTop: "15px",
    },
    between: {
        display: "flex",
        justifyContent: "space-between",
        height: "55px",
    },
    changeButton: {
        height: "100%",
        padding: "0 10px",
        background: "#d7d5d5ab",
        borderRadius: "10px",
        fontSize: "30px",
        color: "gray",
        display: "flex",
        justifyContent: "center",
        cursor: "pointer",
        alignItems: "center",
    },
    change: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    count: {
        height: "100%",
        background: "#EAECEB",
        borderRadius: "10px",
        fontSize: "35px",
        display: "flex",
        justifyContent: "center",
        cursor: "pointer",
        color: "#0c0b0b",
        padding: "0 32px",
        alignItems: "center",
    },
    buttonGroup: {
        display: "flex",
        justifyContent: "space-between",
        height: "55px",
        margin: "14px 0",
    },
    bottomDescription: {
        fontSize: "20px",
        color: "#8f8888",
    },
    infoModal: {
        position: "fixed",
        zIndex: 10,
        background: "#000000a6",
        top: 0,
        right: 0,
        left: 0,
        bottom: 0,
    },
    infoModalCard: {
        height: "100%",
        display: "flex",
        margin: "auto 18px",
    },
    infoModalBody: {
        maxWidth: "670px",
        background: "white",
        borderRadius: "5px",
        margin: "auto",
        width: "100%",
        padding: "20px 15px",
    },
    infoModalTitle: {
        fontSize: "25px",
        fontWeight: 600,
    },
    countTitle: {
        fontSize: "70px",
        fontWeight: 900,
        fontFamily: "Gotham-Bold",
        color: "#000000bd",
    },
    freeTitle: {
        fontSize: "30px",
        fontFamily: "Gotham-Bold",
        lineHeight: "24px",
        fontWeight: 900,
        padding: "0px 0 0 15px",
    },
    freeCardTitle: {
        display: "flex",
        alignItems: "center",
    },
    m0: {
        margin: 0,
    },
    luxCount: {
        fontSize: "20px",
        margin: "15px 10px",
    },
    chooseFont: {
        margin: "10px",
        fontSize: "30px",
        fontWeight: 900,
        lineHeight: "27px",
    },
    freeBonus: {
        textAlign: "center",
        fontSize: "22px",
        fontWeight: 500,
        color: "gray",
        marginBottom: "15px",
    },
    summaryBody: {
        padding: "30px 20px",
    },
    summaryTitle: {
        fontSize: "50px",
        fontWeight: 900,
        fontFamily: "Gotham-Bold",
        color: "gray",
        textAlign: "center",
    },
    summarySubTitle: {
        fontSize: "30px",
        fontWeight: 900,
        fontFamily: "Gotham-Bold",
        textAlign: "center",
        margin: "20px 0 30px 0",
    },
    summaryTopic: {
        fontSize: "25px",
        fontWeight: 900,
        fontFamily: "Gotham-Bold",
        color: "#000000c7",
        margin: "30px 0",
    },
    summaryInfo: {
        display: "flex",
        justifyContent: "space-between",
        fontSize: "25px",
        margin: "20px 0",
        alignItems: "center",
    },
    summaryinfoLeft: {
        fontSize: "16px",
        color: "gray",
    },
    summaryinfoRight: {
        display: "flex",
        justifyContent: "space-between",
        minWidth: "110px",
        marginLeft: "10px",
    },
    summaryDesciption: {
        fontSize: "20px",
        color: "gray",
    },
    close_1: {
        position: "absolute",
        top: "10px",
        left: "10px",
        fontSize: "40px",
        cursor: "pointer",
        color: "#146A26",
    },
    bottomBtnGroup: {
        display: "flex",
        justifyContent: "space-between",
        height: "55px",
        maxWidth: "700px",
        margin: "auto",
    },
    bottomBtn: {
        maxWidth: "120px",
        width: "100%",
        height: "40px",
        borderRadius: "10px",
        cursor: "pointer",
        background: "#06AEC1",
        borderColor: "transparent",
        color: "white",
        fontSize: "15px",
    },
    infoDetail: {
        fontSize: "18px",
        margin: "20px 0",
    },
    mb5: {
        marginBottom: "10px"
    },
    upgradeImage: {
        width: '140px',
        position: 'absolute',
        top: 'calc(50% - 150px)',
        right: 0,
    },
    upgradeImageDiv: {
        width: '100px',
        position: 'relative',
    },
}
